#!/bin/sh

case "$1" in
    start)
        if [ ! -c /dev/spiotp0 ]; then
			mknod /dev/spiotp0 c 10 91
			modprobe spiotp 
        fi
        ;;
    stop)
        ;;
    restart|reload)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

